<h1>Tensor's concept</h1>
Deeplearning as a transformer from one representation to another.</br>
Tensor is a data structure for Pytorch. Tensors are the generalizaion of vectors and matrices to an arbitary numbers of dimensions.</br>
Compared to the Numpy arrays, Pytorch have a few superpowers such as ability to perform very fast operations on graphical processing untis, distribute operations on multople devices or machines.

In [55]:
import torch

In [56]:
#creates a one-dimensional tesnor of size 3 filled with 1s
a=torch.ones(3)
a

tensor([1., 1., 1.])

In [57]:
a[1]

tensor(1.)

In [58]:
float(a[1])
a[2]=2
a

tensor([1., 1., 2.])

Lists and tuples in python are collections of objects. It means that each element might be allocated in diffrenent part of memory.In contrast, Tensor and Arrays's elements are sotred in a continues memeory.

In [59]:
points=torch.tensor([[4,1],[5,3]])


In [60]:
points.shape

torch.Size([2, 2])

In [61]:
points[0,1]

tensor(1)

In [62]:
points[1:]

tensor([[5, 3]])

<h3>Named Tensors</h3>
ie: Converting colored image to gray scale. RGB channnels are located in index of [-3]

In [63]:
img_t=torch.randn(3,5,5)#shape[channels, rows, columns]
weights=torch.tensor([0.2126, 0.7152,0.0722])

In [64]:
batch_t=torch.randn(2,3,5,5)#shape[batch, chanels, rows, columns]

In [65]:
img_gray_naive=img_t.mean(-3)
batch_img_gray_naive=batch_t.mean(-3)
img_gray_naive
batch_img_gray_naive

tensor([[[-0.2554,  0.1765, -0.5528,  0.5690,  0.9700],
         [ 0.2219, -0.5857, -0.3615, -0.7718, -0.2711],
         [ 1.1073, -0.6333, -0.6223,  0.3477, -0.0507],
         [ 1.1219,  0.4698, -0.6062, -1.4743, -1.0756],
         [-1.0320,  0.7256, -0.4783,  0.6332, -0.4183]],

        [[-0.1246,  0.7163,  0.1684,  0.3687, -0.4065],
         [-0.6492, -1.0191,  0.3327,  1.1169,  0.4182],
         [ 0.7979, -0.5157,  0.5973,  0.0659,  1.2550],
         [-0.4614, -0.7576, -0.6590,  0.6857, -0.1096],
         [-0.6544, -0.1189, -0.1236,  0.7037, -0.3521]]])

As pytorch use broadcasting for operations, it is highly recommended to use named indexes for tracking.

In [66]:
NCHW=["N", "C", "H", "W"]
images=torch.randn(3,2,5,5 , names=NCHW)
res=images.sum("C")
res

tensor([[[-1.3982, -1.0144, -0.6110, -0.5449, -0.2121],
         [-1.0982, -1.4431, -1.5409,  1.6746, -3.9580],
         [-0.9680, -0.9913,  2.1736, -1.8231, -0.2546],
         [-1.4500, -0.7750,  0.9510, -2.2770,  0.7449],
         [-0.9007,  3.0159, -0.4198, -0.8948, -0.0720]],

        [[ 1.1935,  1.4958, -0.6159, -0.1874, -1.2557],
         [ 1.3461,  0.2959,  0.6701, -4.3779,  1.3770],
         [ 2.0587,  0.0471, -0.7523, -0.2258, -1.0636],
         [ 0.3870, -0.3050,  0.6634,  1.1794, -1.3126],
         [-2.7136, -0.5562, -1.2149, -2.0520, -2.1819]],

        [[-0.2609,  0.2496,  0.2268, -0.2920, -1.4654],
         [ 0.4176, -2.5598,  1.7939,  2.4022,  2.6392],
         [ 0.7778,  3.0709,  0.9999,  0.6221, -0.1867],
         [ 1.4476, -0.9277, -0.6893,  2.3274, -0.7087],
         [-2.5611, -0.5807, -1.3334, -0.6393, -1.1127]]],
       names=('N', 'H', 'W'))

<h3>Tensor element types</h3>
Numbers in python are objects. It makes prblem when we are dealing with allocating millions of numbers. It is not efficient.</br>
The python interpreter is slow compared to the optimized compled coed.</br>
For these reasons, data science libraries rely on NumPy or introduce dedicated data
structures like PyTorch tensors, which provide efficient low-level implementations of
numerical data structures and related operations on them, wrapped in a convenient
high-level API


In [67]:
double_points=torch.ones(10,2,dtype=torch.double)
short_points=torch.tensor([[1,2],[3,4]],dtype=torch.short)

In [68]:
 short_points.dtype

torch.int16

In [69]:
#casting the datatype
double_points=torch.zeros(10,2).double()

Under the hood, to checks whether the conversion is necessary and, if so, does it.

In [70]:
#the more convinient way
double_points=torch.zeros(10,2).to(torch.double)

<h3>The tensor API</h3>

In [71]:
a=torch.ones(3,2)
#input 1 the tensor 
#input 2 the first dimension to the be transposed
#input 3 the second dimension to be trapsposed
a_t=torch.transpose(a,0,1)

In [72]:
#another way
a.transpose(0,1)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

Transposing in higher dimension

In [86]:
some_t=torch.ones(3,4,5)
transpose_t=some_t.transpose(0,2)
some_t.shape#(3,4,5)
transpose_t.shape#(5,4,3)
some_t.stride()#(20,5,1)
transpose_t.stride()#(1,5,20)

(1, 5, 20)

In [88]:
points=torch.tensor([[1,2],[3,4]])
points_t=points.t()
#t is a function for transforming for two dimensional tensors

indexing into storage

In [73]:
points=torch.tensor([[4 , 1],[5,3],[2,1]])
print(points.storage())
points_storage=points.storage()
points_storage[0]
points.storage()[1]

 4
 1
 5
 3
 2
 1
[torch.storage._TypedStorage(dtype=torch.int64, device=cpu) of size 6]


1

<h3>Inplace modifying</h3>

In [74]:
a=torch.ones(3,2)
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

<h3>Tensor metadata: Size, Offset Stride</h3>
sizes: shape(rows and columns)</br>
offset: the index in the storage corresponding to the first element in the tensor</br>
stride: the numebr of elements in the storage that need to be skipped over to obtain the next element along each dimension.


In [75]:
points=torch.tensor([[4,1],[5,3],[2,1]])
second_point=points[1]
second_point#[5,3]
second_point.storage_offset()#2
second_point.size()

torch.Size([2])

Accessing an element i, j in a 2D tensor results in accessing the storage_offset +
stride[0] * i + stride[1] * j element in the storage.

In [76]:
second_point[0]=10
points

tensor([[ 4,  1],
        [10,  3],
        [ 2,  1]])

In [77]:
#clone
third_point=points[2].clone()
third_point[0]=10
points
#did not change due to working with the clone

tensor([[ 4,  1],
        [10,  3],
        [ 2,  1]])

<h3>Contiguous tensors</h3>
Some tensor operations in PyTorch only work on contiguous tensors, such as view.

In [89]:
points.is_contiguous()

True

In [90]:
points_t.is_contiguous()

False

We can obtain a new contiguous tensor from a non-contiguous one using the contiguous method. When a tensor is transposed, the stride is changed instead of changeing the storage memory. For changing the memory and the way of storing elements of tensors, we can make the storage continueus by contiguous() function.

<h3>Moving tensors to the GPU

In [91]:
#points_gpu=points.to(device="cuda")

RuntimeError: ignored