<h1>Tensor's concept</h1>
Deeplearning as a transformer from one representation to another.</br>
Tensor is a data structure for Pytorch. Tensors are the generalizaion of vectors and matrices to an arbitary numbers of dimensions.</br>
Compared to the Numpy arrays, Pytorch have a few superpowers such as ability to perform very fast operations on graphical processing untis, distribute operations on multople devices or machines.

In [1]:
import torch

In [2]:
#creates a one-dimensional tesnor of size 3 filled with 1s
a=torch.ones(3)
a

tensor([1., 1., 1.])

In [3]:
a[1]

tensor(1.)

In [4]:
float(a[1])
a[2]=2
a

tensor([1., 1., 2.])

Lists and tuples in python are collections of objects. It means that each element might be allocated in diffrenent part of memory.In contrast, Tensor and Arrays's elements are sotred in a continues memeory.

In [5]:
points=torch.tensor([[4,1],[5,3]])


In [6]:
points.shape

torch.Size([2, 2])

In [7]:
points[0,1]

tensor(1)

In [8]:
points[1:]

tensor([[5, 3]])

<h3>Named Tensors</h3>
ie: Converting colored image to gray scale. RGB channnels are located in index of [-3]

In [9]:
img_t=torch.randn(3,5,5)#shape[channels, rows, columns]
weights=torch.tensor([0.2126, 0.7152,0.0722])

In [10]:
batch_t=torch.randn(2,3,5,5)#shape[batch, chanels, rows, columns]

In [11]:
img_gray_naive=img_t.mean(-3)
batch_img_gray_naive=batch_t.mean(-3)
img_gray_naive
batch_img_gray_naive

tensor([[[-0.8820, -0.3340, -0.7684, -0.8244,  1.2831],
         [ 0.4358,  0.4202,  0.0994, -0.8525, -0.1285],
         [ 0.5275,  0.0889, -0.7255, -0.6058,  0.9675],
         [-0.4372, -0.4115,  0.5277, -0.2068,  0.0497],
         [ 0.8654,  0.0507, -0.2174,  0.7621,  0.2029]],

        [[-0.6808,  0.1190,  0.5606,  0.1605, -0.1137],
         [ 0.4778, -0.2832,  0.3680,  0.4493,  0.7533],
         [ 0.0274, -0.6274, -0.1229,  0.0811,  0.3111],
         [-0.6723, -0.0981,  0.0412, -0.1075, -1.2122],
         [ 0.0193, -0.2733, -0.0167, -0.0056,  0.6418]]])

As pytorch use broadcasting for operations, it is highly recommended to use named indexes for tracking.

In [12]:
NCHW=["N", "C", "H", "W"]
images=torch.randn(3,2,5,5 , names=NCHW)
res=images.sum("C")
res

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ../c10/core/TensorImpl.h:1405.)
  


tensor([[[ 0.4079,  3.5985,  2.6656, -1.0257,  0.5434],
         [ 0.6802,  1.7646, -0.1186,  1.4266,  2.4617],
         [-0.0676, -0.9193,  0.2480, -0.2782,  1.4314],
         [-0.5757, -2.0011, -0.9925, -0.2824, -1.8877],
         [-0.3167,  3.4460, -0.1628, -0.5717,  1.4537]],

        [[-1.2671, -0.9157,  0.2197,  0.6138, -1.2123],
         [ 0.1525, -0.4255, -1.1966, -0.1760, -0.7134],
         [ 0.7305, -0.0177, -1.3648,  0.3138,  0.2191],
         [-0.8728, -1.5651,  1.3329, -0.6547, -0.8900],
         [-1.8162, -1.5754,  0.6431, -0.3946, -0.1294]],

        [[-1.1894, -2.7544, -0.0250, -0.7221,  1.4616],
         [-2.1540,  0.5075, -2.1562,  1.8313, -1.0536],
         [ 0.6116, -1.0312,  0.1439,  1.1974,  1.2769],
         [-0.2087,  1.0534,  0.0226, -0.1140, -0.6254],
         [ 2.4064,  1.5018,  1.2040,  0.3349, -1.1291]]],
       names=('N', 'H', 'W'))