In [1]:
import torch

In [2]:
x=torch.randn(3, requires_grad=True)

In [4]:
print(x)

tensor([-1.5105,  0.3469,  0.9362], requires_grad=True)


In [5]:
y=x+2
print(y)

tensor([0.4895, 2.3469, 2.9362], grad_fn=<AddBackward0>)


In [10]:
z=y*y*2
print(x)

tensor([-1.5105,  0.3469,  0.9362], requires_grad=True)


In [7]:
z.backward()

RuntimeError: ignored

error. why? Because the graident is not possible and z should be scalor

In [11]:
z=z.mean()
print(z)

tensor(9.5794, grad_fn=<MeanBackward0>)


In [12]:
#dz/dx
z.backward()

In [14]:
print(x)
print(x.grad)

tensor([-1.5105,  0.3469,  0.9362], requires_grad=True)
tensor([0.6527, 3.1292, 3.9150])


Preventing from tracking the gradinet for x  

In [17]:
#3 ways to detach x 
#x.requires_grad_(False)   Underscore means that changes are inplace
#x.detach
#with torch.no_grad():
y=x.detach()
print(x)
print(y)

tensor([-1.5105,  0.3469,  0.9362], requires_grad=True)
tensor([-1.5105,  0.3469,  0.9362])
